spring:
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.nnwcuhamxjqgmyzptbyb
    password: Qortlqdjr1!

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mhub:
  encryption:
    key: bG9jYWwtZGV2LWVuY3J5cHRpb24ta2V5LTMyY2hhciE=
  cors:
    allowed-origins: http://localhost:5173

# cloud:
#   aws:
#     sqs:
#       endpoint: http://localhost:4566/00000000-0000-0000-0000-000000000000
#     credentials:
#       access-key: test
#       secret-key: test

logging:
  level:
    root: INFO
    com.mhub: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
